### ISSUE TITLE
ParseError: /usr/include/stdint.h:57:1: before: __extension__

### ISSUE THREAD

**Issue by gitttt** [eliben/pycparser#110]
I tried to install panda (https://github.com/moyix/panda) on my Ubuntu 14.04 32bit system. I used the "panda_install_bash" script as recommended from their repository.
The Installation went well up to the point where it said:

Building API for plugin taint
Traceback (most recent call last):
  File "../scripts/apigen.py", line 198, in <module>
    generate_api(plugin, plugin_dir)
  File "../scripts/apigen.py", line 164, in generate_api
    arglist = get_arglists(pf)
  File "../scripts/apigen.py", line 24, in get_arglists
    p = pyc.parse(pf)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/stdint.h:57:1: before: __extension__

In the /usr/include/stdint.h I have:

47   /* Unsigned.  */
48   typedef unsigned char		uint8_t;
49   typedef unsigned short int	uint16_t;
50   #ifndef __uint32_t_defined
51   typedef unsigned int		uint32_t;
52   # define __uint32_t_defined
53   #endif
54   #if __WORDSIZE == 64
55   typedef unsigned long int	uint64_t;
56   #else
57   __extension__
58   typedef unsigned long long int	uint64_t;
59   #endif

Any idea what this error is about?
Thanks for any hints!

**Comment by eliben** [comment]
Sorry I have no idea how that library uses pycparser - I'd open an issue for them instead. FWIW there's stuff about `__extension__` in the FAQ -- https://github.com/eliben/pycparser/wiki/FAQ

**Comment by gitttt** [comment]
Thanks for your fast reply! I will follow your advice and open an issue at the panda repo.
