### ISSUE TITLE
ParseError when condition contains compound

### ISSUE THREAD

**Issue by jfoote** [eliben/pycparser#126]
Thanks for the great tool. I found that the latest version of pycparser fails when parsing a conditional that contains a compound. For example, if the following text is stored in `bug.c`:

```
int foo() {
    return 1;
}
int main(void) {
    int x;
    if(({x = foo();})) {
        return 1;
    }
    return 0;
}
```

It compiles ok via recent `gcc`...

```
$ gcc bug.c
```

... but pycparser fails:
```
$ python -c "from pycparser import parse_file; parse_file('bug.c')" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/redacted/venv/local/lib/python2.7/site-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: bug.c:7:9: before: {
```

Info on my environment:
```
$ pip freeze | grep pycparser
pycparser==2.14
$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The error may be in `ply` but I figured I'd report here first and defer to an expert. Thanks again.

**Comment by kirbyfan64** [comment]
Pycparser intentionally doesn't implement GNU extensions, and compounds are a GNU extension. If you want to parse files like this, try pycparserext.

**Comment by jfoote** [comment]
Ah, TIL about pycparserext. Thanks @kirbyfan64
