### ISSUE TITLE
Parse error on a file starting with /*

### ISSUE THREAD

**Issue by d33tah** [eliben/pycparser#146]
```
[15:42:01]>>> pycparser.parse_file('afl-fuzz.c')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/d33tah/virtualenv/lib/python2.7/site-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: afl-fuzz.c:1:1: before: /
```

Here's afl-fuzz.c:
[afl-fuzz.zip](https://github.com/eliben/pycparser/files/491145/afl-fuzz.zip)

**Comment by kirbyfan64** [comment]
https://github.com/eliben/pycparser/blob/master/README.rst#31interaction-with-the-c-preprocessor

> In order to be compilable, C code must be preprocessed by the C preprocessor - `cpp`. `cpp` handles preprocessing directives like `#include` and `#define`, **removes comments**, and does other minor tasks that prepare the C code for compilation.

**Comment by d33tah** [comment]
Ah! Got it. I used clang's LLVM bindings instead. Thanks.
