### ISSUE TITLE
pycparser-2.15-py2.py3-none-any.whl causes AssertionError: sorry, but this version only supports 100 named groups

### ISSUE THREAD

**Issue by odyssey4me** [eliben/pycparser#151]
It looks like we have a repeat of https://github.com/eliben/pycparser/issues/147 - I'm seeing the same results with the newly uploaded wheel.

**Comment by sp1ky** [comment]
I am also experiencing this with pycparser-2.15-py2.py3-none-any.whl:

```
Collecting pycparser (from cffi>=1.4.1->cryptography)
  Using cached pycparser-2.15-py2.py3-none-any.whl
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... error
    <SNIP>
    File "/tmp/pip-build-dY5W5o/cryptography/.eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 233, in readtab
      titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
    File "/SNIP/lib/python2.7/re.py", line 194, in compile
      return _compile(pattern, flags)
    File "/SNIP/lib/python2.7/re.py", line 249, in _compile
      p = sre_compile.compile(pattern, flags)
    File "/SNIP/lib/python2.7/sre_compile.py", line 583, in compile
      "sorry, but this version only supports 100 named groups"
  AssertionError: sorry, but this version only supports 100 named groups
```

**Comment by eliben** [comment]
I've removed the wheel from PyPI. Not sure what the problem of sre_compile.py is here -- installing the wheel manaully, not through PyPI, worked for me when testing.

**Comment by eliben** [comment]
More details:

After creating the wheel with `bdist_wheel`, I tested with:
`
$ pip install pycparser-2.15-py2.py3-none-any.whl
`

In a virtualenv. And it worked fine. In #147 I made a mistake of creating a wheel for a release from the git master branch where the code was already changed.

... now I also tried to pip install in a fresh virtualenv after pushing to PyPI and didn't see errors. Apparently this error appears when installing pycparser by dependent packages (like cryptography).

I have to say... it's very annoying that such issues only come up through wheel installations in dependent packages. I've never encountered the "only supports 100 named groups" with pycparser in the past.

**Comment by nicorevin** [comment]
> Apparently this error appears when installing pycparser by dependent packages (like cryptography).

exactly...
and `--no-binary pycparser` does not help for some reason this time.

**Comment by jonathan-s** [comment]
Me too.

**Comment by eliben** [comment]
Can any of you folks confirm the problem is gone now? About a minute after deleting the wheel from PyPI I tried to install cryptography and it went through (installing pycparser 2.15 on the way)

**Comment by sp1ky** [comment]
Can confirm, pycparser seems to happily install but cryptography refuses to, regardless of --no-binary:

```
pip install pycparser --no-binary pycparser
Collecting pycparser
  Using cached pycparser-2.15.tar.gz
Skipping bdist_wheel for pycparser, due to binaries being disabled for it.
Installing collected packages: pycparser
  Running setup.py install for pycparser ... done
Successfully installed pycparser-2.15
```
```
pip install cryptography --no-binary cryptography
Collecting cryptography
  Using cached cryptography-1.5.2.tar.gz
...
  Requirement already satisfied (use --upgrade to upgrade): pycparser in /SNIP/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography)
...
Skipping bdist_wheel for cryptography, due to binaries being disabled for it.
Installing collected packages: cryptography
  Running setup.py install for cryptography ... error
  <SNIP>
  File "/SNIP/lib/python2.7/sre_compile.py", line 583, in compile
    AssertionError: sorry, but this version only supports 100 named groups

```

**Comment by pabelanger** [comment]
Can you please tag 2.15.1 and not delete the existing binary?  We've already pulled the wheel into our infrastructure and going to have a hard time manually deleting it.

**Comment by carletes** [comment]
Same issues here right now, I'm afraid :( I need `pycparser` for `cryptography` as well. In case it helps:

```
[..]
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko->-r /root/requirements.txt (line 55))
  Downloading pycparser-2.15.tar.gz (232kB)
[..]
  Running setup.py install for pycparser: started
    Running setup.py install for pycparser: finished with status 'done'
  Running setup.py install for cryptography: started
    Running setup.py install for cryptography: finished with status 'error'
    Complete output from command /usr/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1aWiIc/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-K0_GHY-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1aWiIc/cryptography/setup.py", line 334, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 376, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 181, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 81, in <module>
        extra_link_args=extra_link_args(compiler_type()),
      File "/tmp/pip-build-1aWiIc/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
        extra_link_args=extra_link_args,
      File "/tmp/pip-build-1aWiIc/cryptography/src/_cffi_src/utils.py", line 70, in build_ffi
        ffi.cdef(cdef_source)
      File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 105, in cdef
        self._cdef(csource, override=override, packed=packed)
      File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 119, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/usr/local/lib/python2.7/site-packages/cffi/cparser.py", line 299, in parse
        self._internal_parse(csource)
      File "/usr/local/lib/python2.7/site-packages/cffi/cparser.py", line 304, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "/usr/local/lib/python2.7/site-packages/cffi/cparser.py", line 260, in _parse
        ast = _get_parser().parse(csource)
      File "/usr/local/lib/python2.7/site-packages/cffi/cparser.py", line 40, in _get_parser
        _parser_cache = pycparser.CParser()
      File "/usr/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 87, in __init__
        outputdir=taboutputdir)
      File "/usr/local/lib/python2.7/site-packages/pycparser/c_lexer.py", line 66, in build
        self.lexer = lex.lex(object=self, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/pycparser/ply/lex.py", line 911, in lex
        lexobj.readtab(lextab, ldict)
      File "/usr/local/lib/python2.7/site-packages/pycparser/ply/lex.py", line 233, in readtab
        titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
      File "/usr/local/lib/python2.7/re.py", line 194, in compile
        return _compile(pattern, flags)
      File "/usr/local/lib/python2.7/re.py", line 249, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/local/lib/python2.7/sre_compile.py", line 583, in compile
        "sorry, but this version only supports 100 named groups"
    AssertionError: sorry, but this version only supports 100 named groups
    
    ----------------------------------------
Command "/usr/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1aWiIc/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-K0_GHY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-1aWiIc/cryptography/
```

**Comment by antinescience** [comment]
Same problem here.

**Comment by tbarbugli** [comment]
same issue here; this is probably breaking the internet :)

**Comment by odyssey4me** [comment]
It looks like installing it directly with other requirements still causes a failure:

http://logs.openstack.org/24/388024/4/check/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/2267176/console.html#_2016-10-18_14_09_13_377988

```
2016-10-18 14:09:13.378009 |   Reading http://mirror.iad.rax.openstack.org/pypi/simple/pycparser/
2016-10-18 14:09:13.378051 |   Downloading http://mirror.iad.rax.openstack.org/pypi/packages/37/05/65d342ba500c6f9dbb1978e9dd01a1097530e0291003638bbef329ad4522/pycparser-2.15.tar.gz#md5=8629238be71db4d3f79b4fb1cd1397dc
2016-10-18 14:09:13.378062 |   Best match: pycparser 2.15
2016-10-18 14:09:13.378074 |   Processing pycparser-2.15.tar.gz
2016-10-18 14:09:13.378108 |   Writing /tmp/tmp.MmWXn2YcnP/easy_install-bNKZrP/pycparser-2.15/setup.cfg
2016-10-18 14:09:13.378139 |   Running pycparser-2.15/setup.py -q bdist_egg --dist-dir /tmp/tmp.MmWXn2YcnP/easy_install-bNKZrP/pycparser-2.15/egg-dist-tmp-g4nrZ4
2016-10-18 14:09:13.378162 |   warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
2016-10-18 14:09:13.378192 |   warning: no previously-included files matching 'lextab.*' found under directory 'tests'
2016-10-18 14:09:13.378216 |   warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
2016-10-18 14:09:13.378239 |   warning: no previously-included files matching 'lextab.*' found under directory 'examples'
2016-10-18 14:09:13.378255 |   zip_safe flag not set; analyzing archive contents...
2016-10-18 14:09:13.378269 |   pycparser.ply.lex: module references __file__
2016-10-18 14:09:13.378287 |   pycparser.ply.lex: module MAY be using inspect.getsourcefile
2016-10-18 14:09:13.378301 |   pycparser.ply.yacc: module references __file__
2016-10-18 14:09:13.378318 |   pycparser.ply.yacc: module MAY be using inspect.getsourcefile
2016-10-18 14:09:13.378334 |   pycparser.ply.yacc: module MAY be using inspect.stack
2016-10-18 14:09:13.378349 |   pycparser.ply.ygen: module references __file__
2016-10-18 14:09:13.378372 |   creating /tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg
2016-10-18 14:09:13.378414 |   Extracting pycparser-2.15-py2.7.egg to /tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs
2016-10-18 14:09:13.378421 |   
2016-10-18 14:09:13.378448 |   Installed /tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg
2016-10-18 14:09:13.378462 |   Traceback (most recent call last):
2016-10-18 14:09:13.378477 |     File "<string>", line 1, in <module>
2016-10-18 14:09:13.378503 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/setup.py", line 334, in <module>
2016-10-18 14:09:13.378519 |       **keywords_with_side_effects(sys.argv)
2016-10-18 14:09:13.378540 |     File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
2016-10-18 14:09:13.378556 |       _setup_distribution = dist = klass(attrs)
2016-10-18 14:09:13.378603 |     File "/home/jenkins/workspace/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/.tox/functional/local/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
2016-10-18 14:09:13.378618 |       _Distribution.__init__(self, attrs)
2016-10-18 14:09:13.378640 |     File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
2016-10-18 14:09:13.378652 |       self.finalize_options()
2016-10-18 14:09:13.378700 |     File "/home/jenkins/workspace/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/.tox/functional/local/lib/python2.7/site-packages/setuptools/dist.py", line 376, in finalize_options
2016-10-18 14:09:13.378715 |       ep.load()(self, ep.name, value)
2016-10-18 14:09:13.378754 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 181, in cffi_modules
2016-10-18 14:09:13.378770 |       add_cffi_module(dist, cffi_module)
2016-10-18 14:09:13.378821 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 48, in add_cffi_module
2016-10-18 14:09:13.378857 |       execfile(build_file_name, mod_vars)
2016-10-18 14:09:13.378891 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 24, in execfile
2016-10-18 14:09:13.378902 |       exec(code, glob, glob)
2016-10-18 14:09:13.378919 |     File "src/_cffi_src/build_openssl.py", line 81, in <module>
2016-10-18 14:09:13.378935 |       extra_link_args=extra_link_args(compiler_type()),
2016-10-18 14:09:13.378963 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
2016-10-18 14:09:13.378976 |       extra_link_args=extra_link_args,
2016-10-18 14:09:13.379002 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/src/_cffi_src/utils.py", line 70, in build_ffi
2016-10-18 14:09:13.379013 |       ffi.cdef(cdef_source)
2016-10-18 14:09:13.379043 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 105, in cdef
2016-10-18 14:09:13.379060 |       self._cdef(csource, override=override, packed=packed)
2016-10-18 14:09:13.379091 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 119, in _cdef
2016-10-18 14:09:13.379109 |       self._parser.parse(csource, override=override, **options)
2016-10-18 14:09:13.379141 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 299, in parse
2016-10-18 14:09:13.379153 |       self._internal_parse(csource)
2016-10-18 14:09:13.379187 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 304, in _internal_parse
2016-10-18 14:09:13.379202 |       ast, macros, csource = self._parse(csource)
2016-10-18 14:09:13.379234 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 260, in _parse
2016-10-18 14:09:13.379247 |       ast = _get_parser().parse(csource)
2016-10-18 14:09:13.379280 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 40, in _get_parser
2016-10-18 14:09:13.379296 |       _parser_cache = pycparser.CParser()
2016-10-18 14:09:13.379328 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg/pycparser/c_parser.py", line 87, in __init__
2016-10-18 14:09:13.379339 |       outputdir=taboutputdir)
2016-10-18 14:09:13.379370 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg/pycparser/c_lexer.py", line 66, in build
2016-10-18 14:09:13.379385 |       self.lexer = lex.lex(object=self, **kwargs)
2016-10-18 14:09:13.379416 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 911, in lex
2016-10-18 14:09:13.379428 |       lexobj.readtab(lextab, ldict)
2016-10-18 14:09:13.379459 |     File "/tmp/tmp.MmWXn2YcnP/pip-build-y7s5BI/cryptography/.eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 233, in readtab
2016-10-18 14:09:13.379485 |       titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
2016-10-18 14:09:13.379519 |     File "/home/jenkins/workspace/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/.tox/functional/lib/python2.7/re.py", line 190, in compile
2016-10-18 14:09:13.379532 |       return _compile(pattern, flags)
2016-10-18 14:09:13.379566 |     File "/home/jenkins/workspace/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/.tox/functional/lib/python2.7/re.py", line 242, in _compile
2016-10-18 14:09:13.379580 |       p = sre_compile.compile(pattern, flags)
2016-10-18 14:09:13.379616 |     File "/home/jenkins/workspace/gate-openstack-ansible-tests-ansible-func-ubuntu-trusty/.tox/functional/lib/python2.7/sre_compile.py", line 509, in compile
2016-10-18 14:09:13.379634 |       "sorry, but this version only supports 100 named groups"
2016-10-18 14:09:13.379653 |   AssertionError: sorry, but this version only supports 100 named groups
```

**Comment by tbarbugli** [comment]
`pip install pycparser==2.13` fixes it for me

**Comment by antinescience** [comment]
@tbarbugli thanks, sniping that for our repo as well.

**Comment by sp1ky** [comment]
The 2.14 wheel appears to work when building the cryptography wheel.

```
pip install 'pycparser!=2.15'
pip install cryptography 
```

**Comment by jonathan-s** [comment]
@sp1ky doesn't really work if you have everything in a requirements.txt file.

**Comment by dannosaur** [comment]
The kicker with having it installed via cffi's dependencies is that, not matter what you pin in your requirements file, it stills wants to go and fetch the latest version:

>  [exec]     Installed /tmp/pip-build-kx2gBO/cairocffi/cffi-1.8.3-py2.7-linux-x86_64.egg
     [exec]     Searching for pycparser
     [exec]     Reading https://pypi.python.org/simple/pycparser/
     [exec]     Best match: pycparser 2.15
     [exec]     Downloading https://pypi.python.org/packages/37/05/65d342ba500c6f9dbb1978e9dd01a1097530e0291003638bbef329ad4522/pycparser-2.15.tar.gz#md5=8629238be71db4d3f79b4fb1cd1397dc
     [exec]     Processing pycparser-2.15.tar.gz
     [exec]     Writing /tmp/easy_install-HnwfiH/pycparser-2.15/setup.cfg

This is despite me having `pycparser==2.14` in my requirements.txt.

**Comment by nicorevin** [comment]
@dannosaur try installing pycparser prior running `install -r requirements.txt`

**Comment by GuillaumeT** [comment]
@sp1ky worked for me. note do not forget the quotes otherwise it won't work

**Comment by dannosaur** [comment]
@nicorevin I have no control over this as it's a Jenkins job. Installing manually seems to work, but this has to work within the context of a single `pip install -r requirements.txt` for Jenkins to build the virtualenv up correctly :(

**Comment by michalxptacek** [comment]
can't someone remove broken pycparser 2.15 from pypi repo ?

**Comment by jonathan-s** [comment]
@michalxptacek generally it's better to upgrade to a newer version that's working.

**Comment by pabelanger** [comment]
Please don't remove it like @michalxptacek asked, a revert is fine, but tag it as 2.15.1 or 2.16 please.

**Comment by pabelanger** [comment]
I can confirm what @dannosaur is seeing, trying to figure out why still.

**Comment by GuillaumeT** [comment]
cairocffi is installing latest pycparser. 
if you can `pip install 'pycparser!=2.15'`
prior to `pip install -r requirements.txt`. as @sp1ky suggested

**Comment by michalxptacek** [comment]
Any estimation when there will some working latest version ? If it's simply taking latest version and we can't influence in requirements file, the only way I see as of now is in manual installation before that failing part. We can reconfigure jenkins jobs accordingly if it works, what matters is for how long it will be needed.

**Comment by shulhi** [comment]
@michalxptacek you could just add `pycparser==2.1.4` in the requirements file. I did this as a workaround for now. No wonder my docker build suddenly failed to build :/

**Comment by antinescience** [comment]
@shulhi that doesn't work if you have other dependencies that collect pycparser in their installation, like CairoCFFI. It has to be done in order like:

```
pip install pycparser==2.1.4
pip install -r requirements.txt
```

...or else it'll still fail when it reaches Cairo and tries to gather _its_ dependencies.

**Comment by antinescience** [comment]
For what it's worth, for those of you on Elastic Beanstalk running into this, you can do the following in your `.config` file for your application:

```yaml
commands:
  01_pin_pycparser:
    command: source /opt/python/run/venv/bin/activate && pip install pycparser==2.14
```

This ensures a known, good version of `pycparser` is installed before the requirements are automatically installed by EB. I'm testing this out on a development environment now but I'm fairly certain this works.

**Comment by eliben** [comment]
I pushed v2.16 which should fix the issue, I hope. At least I can now install `cryptography` and see it pulling in 2.16:

```
$ pip install cryptography
...
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography)
  Downloading pycparser-2.16.tar.gz (230kB): 230kB downloaded
...
    Downloading https://pypi.python.org/packages/eb/83/00c55ff5cb773a78e9e47476ac1a0cd2f0fb71b34cb6e178572eaec22984/pycparser-2.16.tar.gz#md5=983118bb558ba11754af25647573487c
    Processing pycparser-2.16.tar.gz
    Writing /tmp/easy_install-nYA70e/pycparser-2.16/setup.cfg
    Running pycparser-2.16/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nYA70e/pycparser-2.16/egg-dist-tmp-n9A1fo
    
    Installed /tmp/vp2/build/cryptography/pycparser-2.16-py2.7.egg
    
...
```

**Comment by mriedem** [comment]
2.16 fixes the issue for me.

**Comment by antinescience** [comment]
@eliben thanks for the fix. Is there any chance we can investigate alternate testing pathways for version bumps of pycparser? Like I said above, I'm happy to help if I can be pointed in the right direction.

**Comment by joechlanda** [comment]
2.16 fixes the issue with cryptography for me as well! Thanks!

**Comment by aaron-trout** [comment]
+1 for 2.16 :D

**Comment by eliben** [comment]
@antinescience What kind of testing would you suggest? I could swear I tried `pip install <wheelname>` in a fresh virtualenv after doing the `sdist` step, which is as close as I can to simulate a pip install.

Also, Travis CI installed and built 2.15 successfully.

I'm open to suggestions on how to test this more before I bump new releases to PyPI.

**Comment by nicorevin** [comment]
@eliben any clue where this `AssertionError` can come from at all?

**Comment by eliben** [comment]
@nicorevin from sre_compile -- the backtrace shows it; but I don't know why it only happens in install situations. I really haven't seen this error before, and pycparser has been on PLY for many years

**Comment by stefanor** [comment]
Interesting data point:

I noticed that if I build the tables with Python 3.x, they don't work on 2.x, because of this issue.

I see Ply has a mechanism to break up complex regexes to stay under the limit. But it does this by experimentally compiling and dividing them. So, if you build the tables with a less restrictive Python (>= 3.5), it'll fail on a more restrictive one (< 3.5).

https://github.com/dabeaz/ply/blob/83c5b91972a0905d620f3407e7d37f4cbcfe4178/ply/lex.py#L343-L378

So, I'd suggest continuing to build these tables under Python 2.7 (or 3.4.x) until 2.7 support is dropped entirely.

**Comment by duisekov** [comment]
@eliben 2.22 facing same problem
