### ISSUE TITLE
when pycparser is parsing clang got an error

### ISSUE THREAD

**Issue by denfromufa** [eliben/pycparser#162]
```
File "tools/geninterop/geninterop.py", line 278, in main
        ast = parser.parse(python_h)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/c_parser.py", line 146, in parse
        debug=debuglevel)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 265, in parse
        return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
        tok = self.errorfunc(errtoken)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/c_parser.py", line 1680, in p_error
        column=self.clex.find_tok_column(p)))
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/plyparser.py", line 55, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: /usr/bin/../lib/clang/3.4/include/stdarg.h:30:27: before: va_list
    Traceback (most recent call last):
```

Originally posted here:

https://github.com/pythonnet/pythonnet/issues/336

**Comment by eliben** [comment]
Please see the pycparser README, FAQ and this blog post: http://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers

**Comment by denfromufa** [comment]
Makes sense, let me try out the suggestion!

**Comment by denfromufa** [comment]
@eliben it turns out exactly same issue - the fake clibs were skipped. Hence the parsing failed.

**Comment by denfromufa** [comment]
@eliben is this error below caused by the same issue or it something new? 

```
Visual C++ for Python//9.0//VC//Include/codeanalysis//sourceannotations.h:69:1: before: [
```

Anyway the included fake headers are not helping. The only difference is that I'm now parsing on Windows with PyPy 2.7 32-bit.

Below is the full traceback from pycparser.

```
clang.exe: warning: C:\Python\pypy2-v5.6.0-win32\include: 'linker' input unused
Traceback (most recent call last):
  File "tools\geninterop\geninterop.py", line 292, in <module>
    sys.exit(main())
  File "tools\geninterop\geninterop.py", line 274, in main
    ast = parser.parse(python_h)
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\c_parser.py", line 151, in parse
    debug=debuglevel)
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\ply\yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\c_parser.py", line 1721, in p_error
    column=self.clex.find_tok_column(p)))
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\pycparser\plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: C://Users//denis//AppData//Local//Programs//Common//Microsoft//Visual C++ for Python//9.0//VC//Include/codeanalysis//sourceannotations.h:69:1: before: [
Traceback (most recent call last):
  File "setup.py", line 408, in <module>
    zip_safe=False,
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\pypy2-v5.6.0-win32\site-packages\wheel\bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\cmd.py", line 334, in run_command
    self.distribution.run_command(command)
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\command\build_ext.py", line 349, in run
    self.build_extensions()
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\distutils\command\build_ext.py", line 458, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 194, in build_extension
    subprocess.check_call([sys.executable, geninterop, interop_file])
  File "C:\Python\pypy2-v5.6.0-win32\lib-python\2.7\subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['C:\\Python\\pypy2-v5.6.0-win32\\pypy.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop27.cs']' returned non-zero exit status 1
```

**Comment by NtAllocateVirtualMemory** [comment]
Also with clang

`pycparser.plyparser.ParseError: C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.40.33807\\include\\vadefs.h:61:34: before: uintptr_t`

```
if source.endswith('.c'):
            raw = parse_file(
                source,
                use_cpp  = True,
                cpp_path = 'clang',
                cpp_args = [
                    '-E',
                    '-std=c99',
                    '-municode',
                    '-I' + utils_dir
                ]
            )

            print(raw.show())
```
