### ISSUE TITLE
cx_Freeze packaging error: could not get source code

### ISSUE THREAD

**Issue by Timtam** [eliben/pycparser#168]
Hi,

I encountered a major issue packaging FFI, which is using pycparser, in one of my projects. It seems that pycparser requires the inspect module to do some fancy AST work, but since cx_Freeze doesn't pack any .py-files to analyze inspect will fail and the whole program doesn't actually finish loading at all.

That's the traceback, using Python 2.7.12 x86 under Windows 10 x64:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", 
line 27, in <module>
    exec(code, m.__dict__)
  File "collisioninspace.py", line 1, in <module>
  File "F:\Privat\Skripte\Collision In Space\lib\__init__.py", line 1, in 
<module>
    from .main import *
  File "F:\Privat\Skripte\Collision In Space\lib\main.py", line 6, in 
<module>
    from .environment import *
  File "F:\Privat\Skripte\Collision In Space\lib\environment.py", line 5, in 
<module>
    import soundbank
  File "F:\Privat\Skripte\Collision In Space\lib\soundbank.py", line 7, in 
<module>
    from sound import *
  File "F:\Privat\Skripte\Collision In Space\lib\sound.py", line 5, in 
<module>
    import soundfile
  File "C:\Python27\lib\site-packages\soundfile.py", line 145, in 
<module>
    """)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 304, in 
_internal_parse
    ast, macros, csource = self._parse(csource)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 260, in _parse
    ast = _get_parser().parse(csource)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 40, in 
_get_parser
    _parser_cache = pycparser.CParser()
  File "C:\Python27\lib\site-packages\pycparser\c_parser.py", line 116, in
__init__
    outputdir=taboutputdir)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 3293, 
in yacc
    if pinfo.validate_all():
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 2938, 
in validate_all
    self.validate_modules()
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 2982, 
in validate_modules
    lines, linen = inspect.getsourcelines(module)
  File "C:\Python27\lib\inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Python27\lib\inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code

Is inspect actually needed to parse the C code, or is it just needed for some special things which FFI actually doesn't need in most cases, so that the importing commands can be excepted and the functionality limited for packaged applications, or anything else?

Do you have some ideas, maybe even some things to forward to the cx_Freeze developers so that this problem can be solved all together?

Best Regards.

**Comment by kirbyfan64** [comment]
This has been fixed in PLY 3.10: https://github.com/dabeaz/ply/issues/97

**Comment by kirbyfan64** [comment]
(meant 3.9)

**Comment by Timtam** [comment]
thanks, using the latest master works like a charm. All right then.
