### ISSUE TITLE
Can't parse Linux Kernel Source (2.6.32)

### ISSUE THREAD

**Issue by 8ohmh** [eliben/pycparser#179]
Hi, tried to parse the Linux Kernel Source by this program:

```
import os
import sys

import pprint
import mmap
import pycparser

from __future__ import print_function
temp_path="/public/linux-kernel/linux-2.6.32.41"

sys.path.extend(['.', '..'])

from pycparser import c_parser, c_ast, parse_file


class FuncDefVisitor(c_ast.NodeVisitor):
	def visit_FuncDef(self, node):
		print('%s at %s' % (node.decl.name, node.decl.coord))


def show_func_defs(filename):
	# Note that cpp is used. Provide a path to your own cpp or
	# make sure one exists in PATH.
	ast = parse_file(filename, use_cpp=True,\
					 cpp_args=r'-Iutils/fake_libc_include')

	v = FuncDefVisitor()
	v.visit(ast)

if __name__ == "__main__":
	start_dir=""
	if len(sys.argv) > 1:
		start_dir = sys.argv[1]

	if len(start_dir) == 0:
		start_dir=temp_path

	for folder, subs, files in os.walk(start_dir):
		for filename in files:
			fpath=os.path.join(folder, filename)
			filename_n, file_extension = os.path.splitext(fpath)
			print file_extension
			if file_extension in [ ".c", ".cc", ".cpp", ".h", ".hpp" ]:
				show_func_defs(fpath)

```
But got as result:
```
Traceback (most recent call last):
  File "func_defs.py", line 61, in <module>
    show_func_defs(fpath)
  File "func_defs.py", line 42, in show_func_defs
    cpp_args=r'-Iutils/fake_libc_include')
  File "/usr/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/lib/python2.7/dist-packages/pycparser/c_parser.py", line 138, in parse
    debug=debuglevel)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1051, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1613, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/lib/python2.7/dist-packages/pycparser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdarg.h:40:27: before: __gnuc_va_list

```
What's wrong?

**Comment by kirbyfan64** [comment]
Pycparser doesn't support GNU extensions. Try using pycparserext:

https://github.com/inducer/pycparserext

**Comment by 8ohmh** [comment]
Thanks but: ... downloaded, installed so far, but how to use? Simply install and use again with the prog above? Tried again, but still not working?
