### ISSUE TITLE
UnicodeDecodeError while installing on Windows in a path containing an "é" 

### ISSUE THREAD

**Issue by JulienPalard** [eliben/pycparser#185]
Hi,

I've seen a user failing to install pycparser 2.17 on a Windows environment using Power Shell, in a fresh python 3.6 venv (native python venv) located in a path containing the letter "é".

```
> py -m pip install pycparser
Collecting pycparser
  Using cached pycparser-2.17.tar.gz
Installing collected packages: pycparser
  Running setup.py install for pycparser ... error
Exception:
Traceback (most recent call last):
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 56: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 56: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Cécile\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Cécile\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\CCIL
E~1\\AppData\\Local\\Temp\\pip-build-fmbcsj3r\\pycparser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Cécile\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Cécile\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Cécile\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Cécile\[redacted]\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)

PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\CCIL
E~1\\AppData\\Local\\Temp\\pip-build-fmbcsj3r\\pycparser'
```

I was unable to reproduce it on Linux, and I no longer have access to a Windows machine, so if someone can reproduce it, it may be worth fixing it.

The short time I had access to the machine told me that `setup.py install` is printing the path in a lot of debug lines, it may print it in latin-1 instead of utf-8, but I didn't had the time to find why.

**Comment by kirbyfan64** [comment]
Bad console encoding? The Windows cmd prompt doesn't support a lot of special characters. (IMO pip/setuptools/distutils shouldn't outright crash, though...)

A fix would be to first run:

```
set PYTHONIOENCODING=:replace
```

**Comment by JulienPalard** [comment]
As I told I no longer have access to this machine. But windows users may not be aware of ``set PYTHONIOENCODING=:replace``, if someone with a windows computer here can try it may help the few with non-ascii characters in their path.
