### ISSUE TITLE
how to parser linux kernel for rewrite ast?

### ISSUE THREAD

**Issue by hoyeunglee** [eliben/pycparser#194]
```
martin@martin-Virtual-Machine:~/Downloads$ python showdef.py 
/home/martin/Downloads/linux-stable/Kconfig:2:3: error: invalid preprocessing directive #For
 # For a description of the syntax of this configuration file,
   ^
/home/martin/Downloads/linux-stable/Kconfig:3:3: error: invalid preprocessing directive #see
 # see Documentation/kbuild/kconfig-language.txt.
   ^
Traceback (most recent call last):
  File "showdef.py", line 61, in <module>
    show_func_defs(os.path.join(path, name))
  File "showdef.py", line 54, in show_func_defs
    ast = parse_file(filename, use_cpp=True,cpp_args=r'-Iutils/fake_libc_include')
  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 151, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1721, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /home/martin/Downloads/linux-stable/Kconfig:5:10: before: "Linux/$ARCH $KERNELVERSION Kernel Configuration"
martin@martin-Virtual-Machine:~/Downloads$ gedit showdef.py 

(gedit:6246): Gtk-WARNING **: GtkScrolledWindow 0x86b0380 is mapped but visible child GtkScrollbar 0x86b2808 is not mapped

(gedit:6246): Gtk-WARNING **: GtkScrolledWindow 0x86b0380 is mapped but visible child GtkScrollbar 0x86b2990 is not mapped

(gedit:6246): Gtk-WARNING **: GtkScrolledWindow 0x86b0380 is mapped but visible child GtkScrollbar 0x86b2808 is not mapped

(gedit:6246): Gtk-WARNING **: GtkScrolledWindow 0x86b0380 is mapped but visible child GtkScrollbar 0x86b2990 is not mapped
martin@martin-Virtual-Machine:~/Downloads$ python showdef.py 
/home/martin/Downloads/linux-stable/virt/kvm/eventfd.c:24:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/vfio.c:13:24: fatal error: linux/file.h: No such file or directory
 #include <linux/file.h>
                        ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/coalesced_mmio.c:11:23: fatal error: kvm/iodev.h: No such file or directory
 #include <kvm/iodev.h>
                       ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/kvm_main.c:19:23: fatal error: kvm/iodev.h: No such file or directory
 #include <kvm/iodev.h>
                       ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/async_pf.c:23:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/irqchip.c:27:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/arch_timer.c:19:23: fatal error: linux/cpu.h: No such file or directory
 #include <linux/cpu.h>
                       ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/pmu.c:18:23: fatal error: linux/cpu.h: No such file or directory
 #include <linux/cpu.h>
                       ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/aarch32.c:24:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/vgic/vgic-mmio-v3.c:14:38: fatal error: linux/irqchip/arm-gic-v3.h: No such file or directory
 #include <linux/irqchip/arm-gic-v3.h>
                                      ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/vgic/vgic-kvm-device.c:16:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
/home/martin/Downloads/linux-stable/virt/kvm/arm/vgic/vgic-irqfd.c:18:28: fatal error: linux/kvm_host.h: No such file or directory
 #include <linux/kvm_host.h>
                            ^
compilation terminated.
Traceback (most recent call last):
  File "showdef.py", line 63, in <module>
    show_func_defs(fullpath)
  File "showdef.py", line 54, in show_func_defs
    ast = parse_file(filename, use_cpp=True,cpp_args=r'-Iutils/fake_libc_include')
  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 151, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1721, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/asm-generic/int-ll64.h:22:20: before: short
martin@martin-Virtual-Machine:~/Downloads$ 

```
```
#-----------------------------------------------------------------

# pycparser: func_defs.py

#

# Using pycparser for printing out all the functions defined in a

# C file.

#

# This is a simple example of traversing the AST generated by

# pycparser. Call it from the root directory of pycparser.

#

# Eli Bendersky [http://eli.thegreenplace.net]

# License: BSD

#-----------------------------------------------------------------

from __future__ import print_function
import sys
import os

# This is not required if you've installed pycparser into
# your site-packages/ with setup.py

sys.path.extend(['.', '..'])

from pycparser import c_parser, c_ast, parse_file





# A simple visitor for FuncDef nodes that prints the names and

# locations of function definitions.

class FuncDefVisitor(c_ast.NodeVisitor):
    def visit_FuncDef(self, node):
        print('%s at %s' % (node.decl.name, node.decl.coord))


def show_func_defs(filename):

    # Note that cpp is used. Provide a path to your own cpp or

    # make sure one exists in PATH.
    ast = parse_file(filename, use_cpp=True,cpp_args=r'-Iutils/fake_libc_include')
    v = FuncDefVisitor()
    v.visit(ast)

if __name__ == "__main__":
    for path, subdirs, files in os.walk("/home/martin/Downloads/linux-stable"):
        for name in files:
            fullpath = os.path.join(path, name)
            if fullpath.endswith(".c"):
                show_func_defs(fullpath)

    
```

**Comment by eliben** [comment]
Please read the README, FAQ and also this post: http://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers
