### ISSUE TITLE
Error importing pycparser since 2.18 update

### ISSUE THREAD

**Issue by dannosaur** [eliben/pycparser#197]
Once again I find my builds and deployments failing due to a new version of pycparser being pulled in as part of another dependency that ends up installing the latest version and failing.

Stack trace:

```
  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/cffi/api.py", line 63, in __init__
    from . import cparser
  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/cffi/cparser.py", line 7, in <module>
    import pycparser

  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/pycparser/__init__.py", line 14, in <module>
    from .c_parser import CParser
  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/pycparser/c_parser.py", line 20, in <module>
    class CParser(PLYParser):
  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/pycparser/plyparser.py", line 95, in template
    _create_param_rules(cls, method)
  File "/srv/www/project/current/.venv/lib/python2.7/site-packages/pycparser/plyparser.py", line 112, in _create_param_rules
    param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
AttributeError: 'NoneType' object has no attribute 'replace'
```
Python 2.7.12
Running inside of uwsgi 2.0.13.1

Let me know if there's anything else you need to know about my environment to help resolve this issue. I've had to pin pycparser in my requirements.txt to 2.17, which works perfectly fine.

**Comment by eliben** [comment]
Does your Python strip docstrings or something like that?

**Comment by dannosaur** [comment]
Not that I'm aware of. I've not gone out of my way to make it do that, or anything of the sort. Just compiled from source using a standard ./configure.

**Comment by eliben** [comment]
This error pattern is consistent with a mode where Python strips docstrings; this happens when Python is run with optimization flags, like `-OO`. I can reproduce the same error when running like that.

I created a virtual env and:

```

$ python --version
Python 2.7.6
$ python tests/all_tests.py 
...................................................................................................
----------------------------------------------------------------------
Ran 99 tests in 3.719s

OK
```

But now if I run with `-OO`, I get:

```
$ python -OO tests/all_tests.py 
Traceback (most recent call last):
  File "tests/all_tests.py", line 15, in <module>
    'test_c_generator',
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/usr/local/google/home/eliben/eli/pycparser/tests/test_c_lexer.py", line 6, in <module>
    from pycparser.c_lexer import CLexer
  File "./pycparser/__init__.py", line 14, in <module>
    from .c_parser import CParser
  File "./pycparser/c_parser.py", line 20, in <module>
    class CParser(PLYParser):
  File "./pycparser/plyparser.py", line 95, in template
    _create_param_rules(cls, method)
  File "./pycparser/plyparser.py", line 112, in _create_param_rules
    param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
AttributeError: 'NoneType' object has no attribute 'replace'

```

**Comment by dannosaur** [comment]
Ah, OK. Our backend server is running uwsgi with "optimize: 2" set. Reading up, that seems to apply the -OO as you describe. So the answer here is to reduce the optimization level of python to 1 (-O) in order to be able to use 2.18+?

**Comment by kirbyfan64** [comment]
Yes. In general, `-OO` can break stuff: https://stackoverflow.com/questions/4777113/what-does-python-optimization-o-or-pythonoptimize-do#comment5290961_4777156

**Comment by dannosaur** [comment]
Alright. Even though I disagree with mandating that docstrings be there, thus forcing people to reduce their optimize level down to compensate for modules that expect them to be there, the solution presented has indeed solved the problem. So I'll close the issue.

**Comment by oliwarner** [comment]
Holy crap, this bug ruined my morning.

We'd been running a website in OO for years and suddenly hit this update with a uwsgi update and the whole thing goes off. Our current testing doesn't cover uwsgi so slipped past us.
