### ISSUE TITLE
Symbol 'id_init_declarator_list_opt' used, but not defined as a token or a rule

### ISSUE THREAD

**Issue by gautaz** [eliben/pycparser#208]
Hello,

I'm currently trying to investigate an issue related to the build process of another tool and I'm getting these errors related to `pycparser`during the build:

```
$ /usr/local/bin/python2 tools/generate_pins.py NUCLEO_F207ZG
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:630: Symbol 'id_init_declarator_list_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:709: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:714: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
ERROR: /usr/local/lib/python2.7/site-packages/pycparser/c_parser.py:719: Symbol 'declaration_specifiers_no_type_opt' used, but not defined as a token or a rule
WARNING: /usr/local/lib/python2.7/site-packages/pycparser/plyparser.py:42: Rule 'specifier_qualifier_list_opt' defined, but not used
WARNING: /usr/local/lib/python2.7/site-packages/pycparser/plyparser.py:42: Rule 'declaration_specifiers_opt' defined, but not used
WARNING: There are 2 unused rules
WARNING: Symbol 'id_init_declarator' is unreachable
WARNING: Symbol 'id_init_declarator_list' is unreachable
WARNING: Symbol 'specifier_qualifier_list_opt' is unreachable
WARNING: Symbol 'declaration_specifiers_opt' is unreachable
ERROR: Infinite recursion detected for symbol 'direct_declarator'
ERROR: Infinite recursion detected for symbol 'declaration_specifiers_no_type'
Traceback (most recent call last):
  File "tools/generate_pins.py", line 247, in <module>
    main()
  File "tools/generate_pins.py", line 237, in main
    pins = enumerate_pins(pins_file, ['./tools'] + list(includes), defines)
  File "tools/generate_pins.py", line 154, in enumerate_pins
    parser=GnuCParser())
  File "/usr/local/lib/python2.7/site-packages/pycparserext/ext_c_parser.py", line 47, in __init__
    debug=yacc_debug, write_tables=False)
  File "/usr/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 3426, in yacc
    raise YaccError('Unable to build parser')
pycparser.ply.yacc.YaccError: Unable to build parser
```

My apologies if this seems a bit off topic but I am wondering if you may have some advice that would help me to find the culprit?

**Comment by eliben** [comment]
Based on the error paths, this comes from https://github.com/inducer/pycparserext
