### ISSUE TITLE
func_defs example appears broken

### ISSUE THREAD

**Issue by Fuzion24** [eliben/pycparser#234]
```
➜  pycparser git:(master) python examples/func_defs.py
In file included from examples/c_files/memmgr.c:8:
examples/c_files/memmgr.h:37:7: warning: missing terminating ' character [-Winvalid-pp-token]
// you'll probably want to keep those undefined, because
      ^
examples/c_files/memmgr.h:96:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif // MEMMGR_H
       ^
       //
examples/c_files/memmgr.c:97:56: warning: missing terminating ' character [-Winvalid-pp-token]
    // that if nbytes is a multiple of nquantas, we don't allocate too much
                                                       ^
examples/c_files/memmgr.c:119:28: warning: missing terminating ' character [-Winvalid-pp-token]
                // its prev's next to its next
                           ^
4 warnings generated.
Traceback (most recent call last):
  File "examples/func_defs.py", line 46, in <module>
    show_func_defs(filename)
  File "examples/func_defs.py", line 34, in show_func_defs
    cpp_args=r'-Iutils/fake_libc_include')
  File "/usr/local/lib/python2.7/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: examples/c_files/memmgr.c:1:1: before: /
```

**Comment by Fuzion24** [comment]
invocation is the first line in the comment ^

**Comment by eliben** [comment]
Can you run this `cpp` on the memmgr.c file with the proper `-I` set (see the sample for how it sets it) and paste the output of `cpp`?

**Comment by Fuzion24** [comment]
```
➜  pycparser git:(master) cpp -Iutils/fake_libc_include/  examples/c_files/memmgr.c 2>&1 | gist -p
https://gist.github.com/7cda28ff9211f320c2605febf5f45003
```

**Comment by Fuzion24** [comment]
stdout : https://gist.github.com/401e94ed6f085e23bdbe2269a031cfa4
stderr: https://gist.github.com/80101c88807a5a55ed2f4fb1d4cfb78e

**Comment by Fuzion24** [comment]
fwiw, if i remove the `//` comment from the file, it seems to work fine.

**Comment by eliben** [comment]
Oh, I see, so your machine's cpp doesn't support c++-style comments?

That's weird, because these are valid in C99, which has been the C standard for a while, and what pycparser supports, officially. Will passing `-std=c99` to cpp help?

**Comment by Fuzion24** [comment]
no, it does not help

**Comment by eliben** [comment]
Strange - it sounds like an issue with your `cpp`. 

The examples are just for demonstration purposes, anyway - they should be easy to tweak to invoke something else as `cpp` (for example `clang -E` is a good option).

If this really bothers you, I'll accept a pull request that replaces C++-style by C-style comments in the sample C files, just to avoid this inconvenience.
