### ISSUE TITLE
'At end of input error'

### ISSUE THREAD

**Issue by davidaharon** [eliben/pycparser#238]
I am trying to parse .i file and getting the following error:
Traceback (most recent call last):

  File "C:/Work/REL_06_02_00_10_exception_after_CFUN_0/Tools/VarsExporter/BuildExportedDb.py", line 1076, in <module>
UNHANDELED EXCEPTION: BuildExportedDb.py
    main()

  File "C:/Work/REL_06_02_00_10_exception_after_CFUN_0/Tools/VarsExporter/BuildExportedDb.py", line 1032, in main
    ast = parse_file(i_file)
  File "C:\Python27\lib\site-packages\pycparser\__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "C:\Python27\lib\site-packages\pycparser\c_parser.py", line 152, in parse
    debug=debuglevel)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python27\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python27\lib\site-packages\pycparser\c_parser.py", line 1763, in p_error
    self._parse_error('At end of input', self.clex.filename)
  File "C:\Python27\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
ParseError: Obj\ServiceDb.i: At end of input

Any suggestions how can I debug it, and find out what's going on?

**Comment by eliben** [comment]
Can you attach the file you're trying to parse, or a minimal reproducer?

**Comment by eliben** [comment]
A common source of confusion is feeding pycparser files that were not preprocessed. Please make sure you read https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

**Comment by davidaharon** [comment]
Thank you,
I have successfully used the method described in your article.

**Comment by eliben** [comment]
You're welcome -- maybe remove the StackOverflow questions you posted in addition to these issues? Or answer yourself to close the question?
