### ISSUE TITLE
Installation on Python 3.7 raises ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by mgeier** [eliben/pycparser#251]
When installing on Python "nightly" on Travis-CI, I see this error:

    ValueError: bad marshal data (unknown type code)

For the full output see https://travis-ci.org/bastibe/SoundFile/jobs/365467380.

I searched a bit for the error message, and the recommended solutions suggest to remove `.pyc` files.

Since the `pycparser` tarball contains `.pyc` files, I guess the error has something to do with them.

But I really don't know, it might be something completely different.

Probably related: #135

**Comment by josephmancuso** [comment]
@eliben Also getting this error. Started around January 24th, 2018 by breaking some builds on Python 3.7-dev. Started testing on that branch again and still breaks

**Comment by eliben** [comment]
@mgeier can you help pinpoint a revision that started breaking? I don't see anything too suspicious around Jan 24 (there's one commit which moves stuff around in the fake includes folder so it shouldn't affect .pyc files)

**Comment by mgeier** [comment]
I kinda thought it was a change in Python version that caused the error to surface.

I was using `pycparser-2.18.tar.gz` all the time (or rather Travis-CI was using it), and with Python versions up to `3.7.0a0` it worked fine.
I saw the error first with Python `3.7.0a4+`.

**Comment by Startouf** [comment]
Hey, I'm getting this error from pycparser 2.18 in Python 3.7.0b3
So, since the pyc seem to be in the tar file, is there some fix that I can apply ?

```
Processing pycparser-2.18.tar.gz
    Writing /tmp/easy_install-v8c6okxf/pycparser-2.18/setup.cfg
    Running pycparser-2.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-v8c6okxf/pycparser-2.18/egg-dist-tmp-mq6qnsbj
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-v8c6okxf/pycparser-2.18/setup.py", line 54, in <module>
        else:
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 218, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 269, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 379, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 416, in scan_module
        code = marshal.load(f)
    ValueError: bad marshal data (unknown type code)
```

**Comment by josephmancuso** [comment]
@Startouf is pycparser installing as a dependency on another package?

**Comment by josephmancuso** [comment]
if it's installing as a dependency of another library, then you should install pycparser by itself first before installing that library. For example:

    $ pip install bcrypt

fails but:

    $ pip install pycparser
    $ pip install bcrypt

will pass and install correctly on Python 3.7.

**Comment by zhaorong1029** [comment]
Excute"sudo find /usr -name '*.pyc' -delete" and retry

**Comment by thenewguy** [comment]
I just started getting this error adding py37 to a test chain.  Was this fixed?

**Comment by GrayWasTaken** [comment]
I am also having this issue when loading a model that was saved on a different version.
