### ISSUE TITLE
Unable to parse provided examples

### ISSUE THREAD

**Issue by jhauberg** [eliben/pycparser#252]
I haven't been able to successfully parse any of the provided examples (that I've tried).

For example:

**func_calls.py**

```
[14:14:58] jhh ~/Downloads/pycparser-master
$ python3 examples/func_calls.py 
Traceback (most recent call last):
  File "examples/func_calls.py", line 46, in <module>
    show_func_calls(filename, func)
  File "examples/func_calls.py", line 33, in show_func_calls
    ast = parse_file(filename, use_cpp=True)
  File "./pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "./pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "./pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "./pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "./pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "./pycparser/c_parser.py", line 1819, in p_error
    column=self.clex.find_tok_column(p)))
  File "./pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: examples/c_files/hash.c:51:5: before: /
```

This was right after downloading current master (https://github.com/eliben/pycparser/commit/902500d126d4732160c46fe525e41c017864f271), without installing.

Same issue occurs after installing to `site-packages`:

```
[14:16:30] jhh ~/Downloads/pycparser-master
$ python3 examples/func_calls.py 
Traceback (most recent call last):
  File "examples/func_calls.py", line 46, in <module>
    show_func_calls(filename, func)
  File "examples/func_calls.py", line 33, in show_func_calls
    ast = parse_file(filename, use_cpp=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/c_parser.py", line 1819, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: examples/c_files/hash.c:51:5: before: /
```

**func_defs.py**

```
[14:29:19] jhh ~/Downloads/pycparser-master
$ python3 examples/func_defs.py 
In file included from examples/c_files/memmgr.c:8:
examples/c_files/memmgr.h:37:7: warning: missing terminating ' character [-Winvalid-pp-token]
// you'll probably want to keep those undefined, because
      ^
examples/c_files/memmgr.h:96:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif // MEMMGR_H
       ^
       //
examples/c_files/memmgr.c:97:56: warning: missing terminating ' character [-Winvalid-pp-token]
    // that if nbytes is a multiple of nquantas, we don't allocate too much
                                                       ^
examples/c_files/memmgr.c:119:28: warning: missing terminating ' character [-Winvalid-pp-token]
                // its prev's next to its next
                           ^
4 warnings generated.
Traceback (most recent call last):
  File "examples/func_defs.py", line 46, in <module>
    show_func_defs(filename)
  File "examples/func_defs.py", line 34, in show_func_defs
    cpp_args=r'-Iutils/fake_libc_include')
  File "./pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "./pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "./pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "./pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "./pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "./pycparser/c_parser.py", line 1819, in p_error
    column=self.clex.find_tok_column(p)))
  File "./pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: examples/c_files/memmgr.c:1:1: before: /
```

This system (MacOS) is using Python 3.5.2.

**EDIT:**

Ok, so I should have done some trivial searching before making this issue. I'm experiencing the exact same as #234.

What fixes it is using either `clang -E` or `gcc` instead of `cpp`:

```
ast = parse_file(filename, use_cpp=True,
                     cpp_path='clang', 
                     cpp_args=['-E', r'-Iutils/fake_libc_include'])
```

**Comment by Aishaaldosery** [comment]
I have the same issue exactly, 

ast = parse_file(filename, use_cpp=True,
                     cpp_path='clang', 
                     cpp_args=['-E', r'-Iutils/fake_libc_include'])

and the parse_file function looks exactly as you post (I didn't change anything ), I use gcc -E for preprocess

**Comment by Aishaaldosery** [comment]
ast = parse_file(filename, use_cpp=True,
            cpp_path='gcc',
            cpp_args=['-E', r'-Iutils/fake_libc_include'])
    ast.show()
 "This is the oroginal file I clone it"
