### ISSUE TITLE
unable to handle extern "C"

### ISSUE THREAD

**Issue by Krace** [eliben/pycparser#283]
Hello,I met the following problem while dump_ast,the source code was:
```
#ifdef __cplusplus
extern "C" {
#endif

#include "goo/gtypes.h"
```

and the error was:
```
Traceback (most recent call last):
  File "examples/dump_ast.py", line 24, in <module>
    ast = parse_file(args.filename, use_cpp=False)
  File "./pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "./pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "./pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "./pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "./pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "./pycparser/c_parser.py", line 1848, in p_error
    column=self.clex.find_tok_column(p)))
  File "./pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: poppler-0.68.0/utils/parseargs.h:28:8: before: "C"
```

What can I do to overcome this..or we can't solve this problem yet. thx :P

**Comment by eliben** [comment]
You have to preprocess the code before parsing it; `extern "C"` is invalid in C, this is why there's a `ifdef __cplusplus` before it

**Comment by Krace** [comment]
I'm sorry,I don't realize that this project is aimed at C only. :)
