### ISSUE TITLE
Parse postgresql -pycparser.plyparser.ParseError before: pgwin32_signal_event

### ISSUE THREAD

**Issue by aditi9292** [eliben/pycparser#289]
I need to parse an open-source project Postgresql using pycparser. 

While parsing its source-code the following error arises:
Traceback (most recent call last):
  File "examples\using_cpp_libc.py", line 48, in <module>
    getAllFiles(projectName)
  File "examples\using_cpp_libc.py", line 29, in getAllFiles
    ast = parse_file(dirName+'\\'+fname, use_cpp = True, cpp_path = 'cpp', cpp_args = [r'-nostdinc',r'-Iutils/fake_libc_include',r'-Iprojects/postgresql/src/include'])
  File "G:\python\pycparser-master\pycparser\__init__.py", line 92, in parse_file
    return parser.parse(text, filename)
  File "G:\python\pycparser-master\pycparser\c_parser.py", line 152, in parse
    debug=debuglevel)
  File "G:\python\pycparser-master\pycparser\ply\yacc.py", line 334, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "G:\python\pycparser-master\pycparser\ply\yacc.py", line 1204, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "G:\python\pycparser-master\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "G:\python\pycparser-master\pycparser\c_parser.py", line 1838, in p_error
    column=self.clex.find_tok_column(p)))
  File "G:\python\pycparser-master\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
**pycparser.plyparser.ParseError: projects/postgresql/src/include/pg_config_os.h:366:15: before: pgwin32_signal_event**

I am using postgresql-9.6.9, build it using visual studio express 2017 on windows 10 (64-bit)

**Comment by eliben** [comment]
Please read

https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

**Comment by aditi9292** [comment]
I have read this tutorial and successfully able to parse Redis using this. However i am not able to resolve error arising while parsing postgresql

**Comment by eliben** [comment]
https://stackoverflow.com/questions/53097804/parse-postgresql-pycparser-plyparser-parseerror-before-pgwin32-signal-event
