### ISSUE TITLE
Why `using_gcc_E_libc.py` does not work outside the source tree?

### ISSUE THREAD

**Issue by pengyu** [eliben/pycparser#302]
`using_gcc_E_libc.py` works fine in `/tmp/pycparser/` source directory. But when I move it out, it does not work anymore. I tried to install pycparser from the source code. But it does not work. Does anybody know what is wrong?

```
/tmp/pycparser$ python setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing pycparser.egg-info/PKG-INFO
writing top-level names to pycparser.egg-info/top_level.txt
writing dependency_links to pycparser.egg-info/dependency_links.txt
reading manifest file 'pycparser.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
writing manifest file 'pycparser.egg-info/SOURCES.txt'
removing '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser-2.19-py2.7.egg-info' (and everything under it)
Copying pycparser.egg-info to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser-2.19-py2.7.egg-info
running install_scripts
Build the lexing/parsing tables

/tmp$ python using_gcc_E_libc.py year.c 
Traceback (most recent call last):
  File "using_gcc_E_libc.py", line 29, in <module>
    cpp_args=['-E', r'-Iutils/fake_libc_include'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/c_parser.py", line 1848, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/i386/_types.h:98:27: before: __darwin_va_list
```

**Comment by kirbyfan64** [comment]
Going to guess it's because pycparser vendors fake includes that are C99 compliant, and when you move it out, it can no longer find them, so it uses the glibc headers that use non-standard extensions.

**Comment by eliben** [comment]
There's a fixed path expectation here: https://github.com/eliben/pycparser/blob/master/examples/using_gcc_E_libc.py#L29

Note that this is just an example - you're supposed to use it as a basis for your own tools. So I'm not trying too hard to make these examples super-generic
