### ISSUE TITLE
get NoneType error in FuncCall visitor example with calling a function without given arguments

### ISSUE THREAD

**Issue by dyhe83** [eliben/pycparser#308]
Hello,

I'm trying [example/func_calls](https://github.com/eliben/pycparser/blob/master/examples/func_calls.py) to visit AST, but get some error in the follow program.
```C
int f1(int) {}
int f2() {}
void f3(void) {}
void f4() {}

int main(void) {
	int n = 3;
	f1(n);
	f2();
	// f3();
	// f4();
	return 0;
}
```
This example works fine when only call `f1(n)`, but it crashed when calling `f2`, `f3` or `f4`.
The Error Message show as follow:

```sh
pycparser/examples$ python3 func_calls.py c_files/test.c f
Traceback (most recent call last):
  File "func_calls.py", line 46, in <module>
    show_func_calls(filename, func)
  File "func_calls.py", line 35, in show_func_calls
    v.visit(ast)
  File "../pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "../pycparser/c_ast.py", line 165, in generic_visit
    self.visit(c)
  File "../pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "../pycparser/c_ast.py", line 165, in generic_visit
    self.visit(c)
  File "../pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "../pycparser/c_ast.py", line 165, in generic_visit
    self.visit(c)
  File "../pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "func_calls.py", line 29, in visit_FuncCall
    self.visit(node.args)
  File "../pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "../pycparser/c_ast.py", line 164, in generic_visit
    for c in node:
TypeError: 'NoneType' object is not iterable
```

**Comment by eliben** [comment]
Thanks for the report. Made the example code a bit more resilient

**Comment by dyhe83** [comment]
Thanks for quick responses!
