### ISSUE TITLE
Same issue when run all the examples

### ISSUE THREAD

**Issue by Aishaaldosery** [eliben/pycparser#319]
Hi, 

I am trying to run the examples provided and I got the same error even with my c files

➜  examples git:(master) ✗ python using_gcc_E_libc.py
Traceback (most recent call last):
  File "using_gcc_E_libc.py", line 29, in <module>
    cpp_args=['-E', r'-Iutils/fake_libc_include'])
  File "../pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "../pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "../pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "../pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "../pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "../pycparser/c_parser.py", line 1848, in p_error
    column=self.clex.find_tok_column(p)))
  File "../pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/i386/_types.h:98:27: before: __darwin_va_list

**Comment by eliben** [comment]
Make sure it actually picks up the fake headers from `utils`. Based on the error you show here it doesn't seem like it - it tries to find files in `/usr/include`.

Try to split it up - run preprocessing first, and then pycparser on the preprocessed files

**Comment by Aishaaldosery** [comment]
I am not sure what the problem is :( still not working even though I reinstall 
1. preprocess the file gcc -E -I utils/fake_libc_include condition.c > condition_pp.c
2.Then on the shell:

>>> from pycparser import parse_file
>>> a = parse_file("condition_pp.c")

 
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    a = parse_file("condition_pp.c")
  File "../pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "../pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "../pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "../pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "../pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "../pycparser/c_parser.py", line 1860, in p_error
    column=self.clex.find_tok_column(p)))
  File "../pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/i386/_types.h:98:27: before: __darwin_va_list
>>>

**Comment by Aishaaldosery** [comment]
and when I ran it on the terminal I got this error:

➜  examples python using_gcc_E_libc.py

clang: error: no such file or directory: 'examples/c_files/year.c'
clang: error: no input files
Traceback (most recent call last):
  File "using_gcc_E_libc.py", line 30, in <module>
    cpp_args=['-E', r'-Iutils/fake_libc_include'])
  File "../pycparser/__init__.py", line 83, in parse_file
    text = preprocess_file(filename, cpp_path, cpp_args)
  File "../pycparser/__init__.py", line 42, in preprocess_file
    text = check_output(path_list, universal_newlines=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['gcc', '-E', '-Iutils/fake_libc_include', 'examples/c_files/year.c']' returned non-zero exit status 1

**Comment by eliben** [comment]
> clang: error: no such file or directory: 'examples/c_files/year.c'

Tells you it can't find that file relative to the current directory. Which directory are you running this from? Running `ls examples` should work and list all examples from the same directory.
