### ISSUE TITLE
 Converting C to AST and then from AST to C

### ISSUE THREAD

**Issue by Buhadod** [eliben/pycparser#320]
Hello,

I was looking at your framework and this tutorial about converting C to AST and then from AST to C. 

https://eli.thegreenplace.net/2011/03/07/from-c-to-ast-and-back-to-c-with-pycparser

I was trying to use it. 

At first I ran the following :

//Converting a code to AST

python dump_ast.py c_files/funky.c > funky_ast

//Convert the AST to C code

python c-to-c.py  funky_ast 

I got some errors as follow : 

Traceback (most recent call last):

  File "c-to-c.py", line 60, in <module>

    translate_to_c(sys.argv[1])

  File "c-to-c.py", line 24, in translate_to_c

    ast = parse_file(filename, use_cpp=True)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 90, in parse_file

    return parser.parse(text, filename)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 152, in parse

    debug=debuglevel)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 331, in parse

    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack

    tok = call_errorfunc(self.errorfunc, errtoken, self)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc

    r = errorfunc(token)

  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1847, in p_error

    column=self.clex.find_tok_column(p)))

  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 67, in _parse_error

    raise ParseError("%s: %s" % (coord, msg))

pycparser.plyparser.ParseError: funky_ast:1:8: before: :

So my quesion , Did I did something wrong, or I missunderstand this tool.

Thank you for you time and I hope you can reply to me.

Regards,

**Comment by Buhadod** [comment]
Thank you for your response.

Yeah, I got your point. but assume we want to do the following :
Convert a a C code .c file to AST and store it as .ast file.
Modify AST (.ast file).
Convert .ast file to C code again.

I still didn't understand how to such an operation as in-memory AST cannot be saved.

**Comment by Buhadod** [comment]
That's great, may I ask you how to modify AST ? as I tried to modify it and
it show me an object of many things.

Regards,
Abdulla

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by eliben** [comment]
Here is an example: https://github.com/eliben/pycparser/blob/master/examples/rewrite_ast.py
