### ISSUE TITLE
parsing for namespace ?

### ISSUE THREAD

**Issue by Tagar** [eliben/pycparser#332]
```
$ autopxd -I /usr/include -I /opt/cloudera/parcels/Anaconda3/include -I /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include -I /usr/include/c++/4.8.2/x86_64-redhat-linux -I /usr/include/c++/4.8.2  VCEUtilities.h VCEUtilities.pxd

Traceback (most recent call last):

. . . .
    r = errorfunc(token)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/c++/4.8.2/bits/memoryfwd.h:50:11: before: std

```

/usr/include/c++/4.8.2/bits/memoryfwd.h
line 50
before std has a keyword `namespace`.

I wonder if pycparser requires .hpp extension for the header files to be processed as C++ and not as C.

**Comment by eliben** [comment]
pycparser only supports C, not C++.
