### ISSUE TITLE
Error  inside _fake_typedefs.h file on the line containing void* declaration while running parse_file function

### ISSUE THREAD

**Issue by shubhamrsangle** [eliben/pycparser#362]
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycparser
>>> pycparser.parse_file('run_pp.c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/c_parser.py", line 1862, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/shubham/Desktop/Windows/BTP/astnn-master/preprocess_pycparser/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: utils/fake_libc_include/_fake_typedefs.h:156:9: before: 1

**Comment by eliben** [comment]
Sorry, this is not a valid issue. You ran the tool on some file and it gave you an error. Sure, that's like opening a bug report vs. a compiler saying "I tried to compile my file (you can't see it) and got this compilation error".

Please open a proper issue with a minimal reproducer if you believe there's a problem with pycparser.
