### ISSUE TITLE
Not able to parse my header file

### ISSUE THREAD

**Issue by XaviLC** [eliben/pycparser#369]
Hello, 

I am facing an issue when try to create a parser for my header file called _Debug.h_ as shown below. However I cannot understand the error itself, could you explain me what the error is trying to say? Is the backslash associated to the comments in _Debug.h_ an issue for the parser?

Thanks in advance,

```
fileName = "C:\\LocalData\\Projects\\git\\firmware\\SDR\\Common\\Debug.h"
ast = parse_file(fileName, use_cpp=False)

ast = parse_file(fileName, use_cpp=False)
Traceback (most recent call last):
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-9c4431fc25a6>", line 1, in <module>
    ast = parse_file(fileName, use_cpp=False)
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\c_parser.py", line 1845, in p_error
    self._parse_error(
  File "C:\LocalData\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: C:\LocalData\Projects\git\firmware\SDR\Common\Debug.h:1:1: before: /
```

**Comment by eliben** [comment]
It's difficult to know without seeing what's in the file. Try to isolate this by extracting a small snippet from the file that produces this error and post it here.

**Comment by XaviLC** [comment]
HI @eliben  thanks for the reply, I found the issue. The file itself seemed to have a wrong trailing character...
