### ISSUE TITLE
AttributeError: 'ID' object has no attribute 'type'

### ISSUE THREAD

**Issue by BelgacemNajib** [eliben/pycparser#371]
i need to lint my code that contains a lots of function defined like : 

int function( myString )
char* myString ;{
// code here
}

my gcc is able to compile this kind of prototype but pycparser returns this error : 
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "testLinter.py", line 88, in <module>
    show_func_defs(filename)
  File "testLinter.py", line 79, in show_func_defs
    v.visit(ast)
  File "Python37\lib\site-packages\pycparser\c_ast.py", line 158, in visit
    return visitor(node)
  File "Python37\lib\site-packages\pycparser\c_ast.py", line 165, in generic_visit
    self.visit(c)
  File "Python37\lib\site-packages\pycparser\c_ast.py", line 158, in visit
    return visitor(node)
  File "testLinter.py", line 43, in visit_FuncDef
    if type(params.type) is c_ast.PtrDecl:
AttributeError: 'ID' object has no attribute 'type'
--------------------------------------------------------------------------------------------------------

any help please 
thank you

**Comment by eliben** [comment]
This is not standard C, it's old K&R C which predates the C standard. pycparser only supports standard C.
