### ISSUE TITLE
"typedef int  __int128;" Fails with ParseError: Invalid Declaration

### ISSUE THREAD

**Issue by DylanYoung** [eliben/pycparser#380]
Seems very specific to the number 128 and double underscore; haven't been able to reproduce with any other example.

Traceback:
```
>>> p.parse("typedef int  __int128;")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/c_parser.py", line 715, in p_decl_body
    typedef_namespace=True)
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/c_parser.py", line 402, in _build_declarations
    self._parse_error('Invalid declaration', coord)
  File "/usr/local/Cellar/python3/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :1:9: Invalid declaration
```

**Comment by eliben** [comment]
This is because `__int128` is already natively recognized as a type (see https://github.com/eliben/pycparser/pull/158), making this code invalid.

**Comment by DylanYoung** [comment]
Hmmm... then there are other issues I'm facing as it isn't recognized.   I'm using pycparser_ext though so I'll follow up if I trace the issue back to here.

**Comment by DylanYoung** [comment]
Ah I think I have an idea what the problem is. Maybe a fix in CFFI is in order to support this type. 

Thanks!
