### ISSUE TITLE
pycparser get an error when parse openssl/ssl/bio_ssl.c

### ISSUE THREAD

**Issue by ycdxsb** [eliben/pycparser#397]
I want to parse this file https://github.com/openssl/openssl/blob/master/ssl/bio_ssl.c
First, I use command below to preprocess it because there are so many head files in openssl project.
```
gcc  -E -I. -Iinclude  -DAES_ASM -fPIC -pthread -m64 -Wa,--noexecstack -Wall -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF ssl/libssl-lib-bio_ssl.d.tmp -MT ssl/libssl-lib-bio_ssl.o -c  ssl/bio_ssl.c > bio_ssl_pp.c
```
Then I get `bio_ssl_pp.c` 
[bio_ssl_pp.c.zip](https://github.com/eliben/pycparser/files/5559511/bio_ssl_pp.c.zip), and I parse it with code below.
```
from __future__ import print_function
import sys

from pycparser import c_parser, c_ast, parse_file

if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename  = sys.argv[1]
    else:
        exit(0)
    ast = parse_file(filename)
```
Finally, I get error log like this. Can you help me with it?
```
Traceback (most recent call last):
  File "exp.py", line 11, in <module>
    ast = parse_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/c_parser.py", line 1861, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python3.5/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h:40:27: before: __gnuc_va_list
```

**Comment by ycdxsb** [comment]
Now I use -nostdinc to make gcc include fake header first ,the command and error are like this.(ref:https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers)
```
gcc -nostdinc -E -I/root/source_code_process/cparser/utils/fake_libc_include -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I. -Iinclude -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu/ -I/usr/include/  -DAES_ASM -fPIC -pthread -m64 -Wa,--noexecstack -Wall -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF ssl/libssl-lib-bio_ssl.d.tmp -MT ssl/libssl-lib-bio_ssl.o -c  ssl/bio_ssl.c > bio_ssl_pp2.c
```

```
Traceback (most recent call last):
  File "exp.py", line 11, in <module>
    ast = parse_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.5/dist-packages/pycparser/c_parser.py", line 1861, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python3.5/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: include/openssl/safestack.h:201:256: before: (
```
Howerver, It seems ok at `include/openssl/safestack.h:201`
[attachment.zip](https://github.com/eliben/pycparser/files/5559750/attachment.zip)

**Comment by eliben** [comment]
It seems like some GNU extensions are still used. You can either `#define` them away (please read https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/ carefully and understand all the examples), or use something like https://github.com/inducer/pycparserext
