### ISSUE TITLE
Possible issue with pre-processing with cpp

### ISSUE THREAD

**Issue by akash-isu** [eliben/pycparser#410]
I'm trying to run the examples c-to-c and c_json. However, I keep running into similar errors. 
I'm on Ubuntu 20.04 with gcc 9.3.
Here's the traceback for the c_json run:

Traceback (most recent call last):
  File "main.py", line 161, in <module>
    ast_dict = file_to_dict(sys.argv[1])
  File "main.py", line 95, in file_to_dict
    ast = parse_file(filename, use_cpp=True)
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 1858, in p_error
    self._parse_error(
  File "/home/akashdutta/.local/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h:40:27: before: __gnuc_va_list

**Comment by eliben** [comment]
Please read https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

If the problem persists, reopen the issue and add a minimal reproducible example

**Comment by akash-isu** [comment]
I have gone through this document. It mentions "If your code is standards-compliant C, then most likely pycparser will have no issue parsing all your headers." And mine is a very simple program (given below). For a program as simple as this, do I still need the fake headers?

#include <stdio.h>

int main()
{
  int x[100000], i;
  for (i = 0; i < 100000; ++i) {
    x[i] = 42;
  }

  for (i = 0; i < 100000; ++i) {
    x[i] = 1;
  }
  printf("After execution, x[0] = %d\n", x[0]);
  return 0;
}
