### ISSUE TITLE
"before: __gnuc_va_list" error

### ISSUE THREAD

**Issue by 4docsforge-docs** [eliben/pycparser#432]
Hello.

When i parse c file, using pycparser, i got error:

Traceback (most recent call last):
  File "D:\Projects\python_c_parsing\func_defs.py", line 50, in <module>
    show_func_defs(filename)
  File "D:\Projects\python_c_parsing\func_defs.py", line 37, in show_func_defs
    ast = parse_file(filename, use_cpp=True,
  File "C:\Python39x64\lib\site-packages\pycparser\__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "C:\Python39x64\lib\site-packages\pycparser\c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "C:\Python39x64\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python39x64\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Python39x64\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Python39x64\lib\site-packages\pycparser\c_parser.py", line 1858, in p_error
    self._parse_error(
  File "C:\Python39x64\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: C:/msys64/mingw64/x86_64-w64-mingw32/include/vadefs.h:24:28: before: __gnuc_va_list
PS D:\Projects\python_c_parsing>

PS D:\Projects\python_c_parsing>gcc -E file_with_code.c > file_with_code_pp.c

gcc -E gave results without errors (i did it, using https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers). 

But when i called  func_defs.py  file_with_code_pp.c i got many errors:

<stdin>:98:8: error: "6" is not a valid filename
<stdin>:110:8: error: "8" is not a valid filename
<stdin>:186:8: error: "0" is not a valid filename
<stdin>:188:8: error: "6" is not a valid filename
<stdin>:194:8: error: "8" is not a valid filename
<stdin>:358:8: error: "5" is not a valid filename
<stdin>:400:8: error: "0" is not a valid filename
In file included from <stdin>:402,
                 from <stdin>:72,
                 from <stdin>:460,
                 from <stdin>:884,

How can i solve it?

**Comment by 4docsforge-docs** [comment]
I used gcc -E output for func_defs.py, according https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers, and got result.

Sorry, please, remove issue

**Comment by eliben** [comment]
The issues title talks about `__gnuc_va_list` -- does this get resolved when you do the preprocessing?

Please attach a minimal example that demonstrates your problem

**Comment by eliben** [comment]
I asked for a *minimal* example and you attach a 6.5 MB file...

At no place does pycparser guarantee that it'll be able to parse any random pile of code with enormous system libraries. As the blog post you linked demonstrates explains, this needs some work on your end.

If you find what you believe is a bug in pycparser or something from standard C it does not support, please open a new issue with a _**minimal**_ example (up to 20 lines of code).

**Comment by daniel57060** [comment]
A simple "hello world" doesn't works. They throws the same error messsage unfortunatelly.

main.py:

```py
import pycparser
from pathlib import Path

result = pycparser.parse_file(Path(__file__).parent / "hello.c", use_cpp=True)
print(result)
```

hello.c:

```c
#include <stdio.h>

int main()
{
    printf("Hello, world!\n");
    return (0);
}
```

Error:

```
Traceback (most recent call last):
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/main.py", line 7, in <module>
    result = pycparser.parse_file(examples_dir / "hello.c", use_cpp=True)
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/__init__.py", line 90, in parse_file    
    return parser.parse(text, filename)
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/c_parser.py", line 147, in parse        
    return self.cparser.parse(
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse        
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/c_parser.py", line 1931, in p_error     
    self._parse_error(
  File "/mnt/e/DISK/BCC/IPB/master/implementation/parsers/pycparser/lvenv/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error 
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h:40:27: before: __gnuc_va_list
```

**Comment by daniel57060** [comment]
I see that when I do "pip install pycparser" the folder "utils" was not retrieved together. I do a clone from the repository and I set the cpp_args manually to works. This can be resolved without need do a clone of the repository?

```py
import pycparser
from pathlib import Path

result = pycparser.parse_file(Path(
    __file__).parent / "hello.c", use_cpp=True, cpp_args='-Ipycparser/utils/fake_libc_include')
print(result)
```
