### ISSUE TITLE
Parser Error in stdarg.h with __gnuc_va_list with gcc 11 and Python 3.10

### ISSUE THREAD

**Issue by scorpion81** [eliben/pycparser#452]
Hello :slightly_smiling_face: 
Using this minimal example script (save it as test.py)

```
#!/usr/bin/env python3

import pycparser

result = pycparser.preprocess_file("test.h")
with open("out.h", "w+") as fp:
    print(result, file=fp)
ast = pycparser.parse_file("out.h")
```

with this test code (save it as test.h)
```
/*
* comment
*/

#include <stdio.h>

struct test1 {
    int blah;
    float blub;
} t5;

struct {
    double x;
    double y;
} t6;

typedef struct test2 {
    char* pointer;
} test3;

struct test4 {
    int x;
    struct test1 t;
    test3* t2;
};
```

i hit following errors:
```
Traceback (most recent call last):
  File "/home/xxx/Projekte/code-analyzer/./test.py", line 8, in <module>
    ast = pycparser.parse_file("out.h")
  File "/usr/lib/python3.10/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/usr/lib/python3.10/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.10/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/usr/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:40:27: before: __gnuc_va_list
```

As you might see from the stack trace, i am using gcc 11.1 and python 3.10 under Manjaro Linux with Kernel 5.15.

And yes, I found a similar issue already here : https://github.com/eliben/pycparser/issues/432 . But I was thinking, for reason of cleanlyless I might open a new issue instead of appending another comment to this existing issue.

**Comment by scorpion81** [comment]
Ok, apologies for me being stupid.... Lol... i did mistakenly assumed cpp refers to C++ here and not the C Preprocessor :joy: 
Cloning this repo to get the fake includes and correctly invoking the parser including the preprocessor like this
```
ast = pycparser.parse_file("test.h", use_cpp=True, cpp_args=r'-I../pycparser/utils/fake_libc_include')
```
let my test file being parsed properly.

**Comment by scorpion81** [comment]
Closing now, since it seems to work as expected.

**Comment by kadn** [comment]
thank you !!!
