### ISSUE TITLE
Pypy, but not cPython, gives "YaccError: Unable to build parser" when PYTHONOPTIMIZED=2 

### ISSUE THREAD

**Issue by fomcl** [eliben/pycparser#454]
Hi,

I was importing some Crypto stuff with pypy3, with -OO (PYTHONOPTIMIZED=2) startup option and I got an error `cffi._pycparser.ply.yacc.YaccError: Unable to build parser`. CPython 3.8 did not throw an error with the same start up option. Is this a bug?

Thanks!

```
## cPython 3.8
c:\>python --version
Python 3.8.8
c:\>set pythonoptimize=0
c:\>python -c "from Crypto.Hash import SHA256"
c:\>set pythonoptimize=1
c:\>python -c "from Crypto.Hash import SHA256"
c:\>set pythonoptimize=2
c:\>python -c "from Crypto.Hash import SHA256"

## PyPy 3.8
c:\>pypy --version
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:12:27)
[PyPy 7.3.7 with MSC v.1929 64 bit (AMD64)]
c:\>set pythonoptimize=0
c:\>pypy -c "from Crypto.Hash import SHA256"
c:\>set pythonoptimize=1
c:\>pypy -c "from Crypto.Hash import SHA256"
c:\>set pythonoptimize=2
c:\>pypy -c "from Crypto.Hash import SHA256"
c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:20: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
WARNING: There was a problem loading the table file: KeyError('p_direct_id_declarator_1')
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:513: No documentation string specified in function 'p_translation_unit_or_empty' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:522: No documentation string specified in function 'p_translation_unit_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:529: No documentation string specified in function 'p_translation_unit_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:540: No documentation string specified in function 'p_external_declaration_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:545: No documentation string specified in function 'p_external_declaration_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:550: No documentation string specified in function 'p_external_declaration_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:556: No documentation string specified in function 'p_external_declaration_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:561: No documentation string specified in function 'p_pp_directive' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:567: No documentation string specified in function 'p_pppragma_directive' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:579: No documentation string specified in function 'p_function_definition_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:596: No documentation string specified in function 'p_function_definition_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:607: No documentation string specified in function 'p_statement' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:660: No documentation string specified in function 'p_pragmacomp_or_statement' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:680: No documentation string specified in function 'p_decl_body' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:740: No documentation string specified in function 'p_declaration' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:749: No documentation string specified in function 'p_declaration_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:760: No documentation string specified in function 'p_declaration_specifiers_no_type_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:765: No documentation string specified in function 'p_declaration_specifiers_no_type_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:770: No documentation string specified in function 'p_declaration_specifiers_no_type_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:776: No documentation string specified in function 'p_declaration_specifiers_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:781: No documentation string specified in function 'p_declaration_specifiers_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:786: No documentation string specified in function 'p_declaration_specifiers_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:791: No documentation string specified in function 'p_declaration_specifiers_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:796: No documentation string specified in function 'p_declaration_specifiers_5' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:801: No documentation string specified in function 'p_declaration_specifiers_6' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:807: No documentation string specified in function 'p_storage_class_specifier' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:816: No documentation string specified in function 'p_function_specifier' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:821: No documentation string specified in function 'p_type_specifier_no_typeid' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:837: No documentation string specified in function 'p_type_specifier' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:845: No documentation string specified in function 'p_type_qualifier' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:852: No documentation string specified in function 'p_init_declarator_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:861: No documentation string specified in function 'p_init_declarator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:867: No documentation string specified in function 'p_id_init_declarator_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:873: No documentation string specified in function 'p_id_init_declarator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:881: No documentation string specified in function 'p_specifier_qualifier_list_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:886: No documentation string specified in function 'p_specifier_qualifier_list_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:891: No documentation string specified in function 'p_specifier_qualifier_list_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:896: No documentation string specified in function 'p_specifier_qualifier_list_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:905: No documentation string specified in function 'p_struct_or_union_specifier_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:916: No documentation string specified in function 'p_struct_or_union_specifier_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:934: No documentation string specified in function 'p_struct_or_union_specifier_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:953: No documentation string specified in function 'p_struct_or_union' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:961: No documentation string specified in function 'p_struct_declaration_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:970: No documentation string specified in function 'p_struct_declaration_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1008: No documentation string specified in function 'p_struct_declaration_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1013: No documentation string specified in function 'p_struct_declaration_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1018: No documentation string specified in function 'p_struct_declarator_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1027: No documentation string specified in function 'p_struct_declarator_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1032: No documentation string specified in function 'p_struct_declarator_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1041: No documentation string specified in function 'p_enum_specifier_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1047: No documentation string specified in function 'p_enum_specifier_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1052: No documentation string specified in function 'p_enum_specifier_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1058: No documentation string specified in function 'p_enumerator_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1071: No documentation string specified in function 'p_enumerator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1087: No documentation string specified in function 'p_declarator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1199: No documentation string specified in function 'p_pointer' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1229: No documentation string specified in function 'p_type_qualifier_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1235: No documentation string specified in function 'p_parameter_type_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1244: No documentation string specified in function 'p_parameter_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1264: No documentation string specified in function 'p_parameter_declaration_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1276: No documentation string specified in function 'p_parameter_declaration_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1307: No documentation string specified in function 'p_identifier_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1317: No documentation string specified in function 'p_initializer_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1322: No documentation string specified in function 'p_initializer_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1331: No documentation string specified in function 'p_initializer_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1343: No documentation string specified in function 'p_designation' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1351: No documentation string specified in function 'p_designator_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1357: No documentation string specified in function 'p_designator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1363: No documentation string specified in function 'p_type_name' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1374: No documentation string specified in function 'p_abstract_declarator_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1382: No documentation string specified in function 'p_abstract_declarator_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1387: No documentation string specified in function 'p_abstract_declarator_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1397: No documentation string specified in function 'p_direct_abstract_declarator_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1401: No documentation string specified in function 'p_direct_abstract_declarator_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1412: No documentation string specified in function 'p_direct_abstract_declarator_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1422: No documentation string specified in function 'p_direct_abstract_declarator_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1433: No documentation string specified in function 'p_direct_abstract_declarator_5' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1442: No documentation string specified in function 'p_direct_abstract_declarator_6' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1452: No documentation string specified in function 'p_direct_abstract_declarator_7' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1463: No documentation string specified in function 'p_block_item' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1471: No documentation string specified in function 'p_block_item_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1478: No documentation string specified in function 'p_compound_statement_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1484: No documentation string specified in function 'p_labeled_statement_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1488: No documentation string specified in function 'p_labeled_statement_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1492: No documentation string specified in function 'p_labeled_statement_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1496: No documentation string specified in function 'p_selection_statement_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1500: No documentation string specified in function 'p_selection_statement_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1504: No documentation string specified in function 'p_selection_statement_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1509: No documentation string specified in function 'p_iteration_statement_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1513: No documentation string specified in function 'p_iteration_statement_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1517: No documentation string specified in function 'p_iteration_statement_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1521: No documentation string specified in function 'p_iteration_statement_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1526: No documentation string specified in function 'p_jump_statement_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1530: No documentation string specified in function 'p_jump_statement_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1534: No documentation string specified in function 'p_jump_statement_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1538: No documentation string specified in function 'p_jump_statement_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1544: No documentation string specified in function 'p_expression_statement' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1551: No documentation string specified in function 'p_expression' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1564: No documentation string specified in function 'p_typedef_name' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1568: No documentation string specified in function 'p_assignment_expression' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1582: No documentation string specified in function 'p_assignment_operator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1597: No documentation string specified in function 'p_constant_expression' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1601: No documentation string specified in function 'p_conditional_expression' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1610: No documentation string specified in function 'p_binary_expression' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1636: No documentation string specified in function 'p_cast_expression_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1640: No documentation string specified in function 'p_cast_expression_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1644: No documentation string specified in function 'p_unary_expression_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1648: No documentation string specified in function 'p_unary_expression_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1655: No documentation string specified in function 'p_unary_expression_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1664: No documentation string specified in function 'p_unary_operator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1674: No documentation string specified in function 'p_postfix_expression_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1678: No documentation string specified in function 'p_postfix_expression_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1682: No documentation string specified in function 'p_postfix_expression_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1688: No documentation string specified in function 'p_postfix_expression_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1697: No documentation string specified in function 'p_postfix_expression_5' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1703: No documentation string specified in function 'p_postfix_expression_6' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1709: No documentation string specified in function 'p_primary_expression_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1713: No documentation string specified in function 'p_primary_expression_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1717: No documentation string specified in function 'p_primary_expression_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1723: No documentation string specified in function 'p_primary_expression_4' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1727: No documentation string specified in function 'p_primary_expression_5' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1735: No documentation string specified in function 'p_offsetof_member_designator' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1749: No documentation string specified in function 'p_argument_expression_list' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1759: No documentation string specified in function 'p_identifier' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1763: No documentation string specified in function 'p_constant_1' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1786: No documentation string specified in function 'p_constant_2' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1803: No documentation string specified in function 'p_constant_3' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1815: No documentation string specified in function 'p_unified_string_literal' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1826: No documentation string specified in function 'p_unified_wstring_literal' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1837: No documentation string specified in function 'p_brace_open' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1843: No documentation string specified in function 'p_brace_close' (ignored)
WARNING: c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:1849: No documentation string specified in function 'p_empty' (ignored)
ERROR: start symbol translation_unit_or_empty undefined
Traceback (most recent call last):
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\api.py", line 183, in _typeof
    result = self._parsed_types[cdecl]
KeyError: 'const uint8_t*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\files\Crypto\Hash\SHA256.py", line 23, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "c:\files\Crypto\Util\_raw_api.py", line 83, in <module>
    uint8_t_type = ffi.typeof(ffi.new("const uint8_t*"))
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\api.py", line 266, in new
    cdecl = self._typeof(cdecl)
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\api.py", line 186, in _typeof
    result = self._typeof_locked(cdecl)
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\api.py", line 171, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\cparser.py", line 552, in parse_type
    return self.parse_type_and_quals(cdecl)[0]
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\cparser.py", line 555, in parse_type_and_quals
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\cparser.py", line 336, in _parse
    ast = _get_parser().parse(fullcsource)
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\cparser.py", line 53, in _get_parser
    _parser_cache = pycparser.CParser()
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py", line 117, in __init__
    outputdir=taboutputdir)
  File "c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\ply\yacc.py", line 3352, in yacc
    raise YaccError('Unable to build parser')
cffi._pycparser.ply.yacc.YaccError: Unable to build parser
```

**Comment by eliben** [comment]
There's even a helpful warning at the beginning of your log:

> c:\files\pypy3.8-v7.3.7-win64\Lib\cffi\_pycparser\c_parser.py:20: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly

**Comment by fomcl** [comment]
Aah... sorry, I see it now. My mistake. :-)
