### ISSUE TITLE
Parsing C files with comments throws error

### ISSUE THREAD

**Issue by zeeshanr97** [eliben/pycparser#460]
Whenever C files contain comment or comments then the parser halts and throws the  following error:
Traceback (most recent call last):
  File "testPa.py", line 21, in <module>
    ast = parse_file(args.filename, use_cpp=False)
  File "C:\python3\lib\site-packages\pycparser\__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "C:\python3\lib\site-packages\pycparser\c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "C:\python3\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\python3\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\python3\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\python3\lib\site-packages\pycparser\c_parser.py", line 1858, in p_error
    self._parse_error(
  File "C:\python3\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: main.c:24:3: before: /

**Comment by zengshaokun** [comment]
Hello! I get the same problem. Have you found the solution?

**Comment by zeeshanr97** [comment]
No, I'll try to add the comment parsing code myself but in any case this issue should be fixed.

**Comment by JulianKemmerer** [comment]
Is the solution to run the c pre processor?

**Comment by eliben** [comment]
This is described right in the README: https://github.com/eliben/pycparser#3using

Also read the blog post linked in section 3.2
