### ISSUE TITLE
Unable to run pycparser/examples/using_cpp_libc.py and using_gcc_E_libc.py on Ubuntu

### ISSUE THREAD

**Issue by MaggieCwj** [eliben/pycparser#462]
I run pycparser/examples/using_cpp_libc.py and using_gcc_E_libc.py to parse c_files/year.c on Windows successfully.
However, I do the same on Ubuntu and failed. 

The following is the error message on Ubuntu

```
Traceback (most recent call last):
  File "using_cpp_libc.py", line 29, in <module>
    cpp_args=r'-Iutils/fake_libc_include')
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/c_parser.py", line 1861, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/nkamg/.local/lib/python3.6/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h:40:27: before: __gnuc_va_list
```

**Comment by eliben** [comment]
Sorry, I can't reproduce it - it works fine on my Ubuntu machine. The tests also verify all examples run on Linux.

I'm concerned it shows it's going to the gcc include dir - it should be using the fake headers instead.

**Comment by MaggieCwj** [comment]
I solve it by install the latest version in github. However, i met a new problem. 
Pycparser has many problems in generating the ast of base64 of lava-m even if I include all the header file folders base64 needs. such as:

`Traceback (most recent call last):
  File "using_gcc_E_libc.py", line 30, in <module>
    cpp_args=['-nostdinc', '-E', r'-Ipycparser/utils/fake_libc_include', r'-Ibase64/lib', r'-Ibase64/lib/sys', r'-I/usr/include'])
  File "/usr/local/lib/python3.6/dist-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/c_parser.py", line 150, in parse
    debug=debug)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/c_parser.py", line 1934, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python3.6/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: base64/lib/timespec.h:77:27: before: (
`
I wanna know how to solve these problems? Thank you😊

**Comment by kadn** [comment]
I met the same problem on my PC.  I used the latest version but it didn't work.
The different place is that my environment is in a DOCKER. How can I solve it?

**Comment by kadn** [comment]
> I met the same problem on my PC. I used the latest version but it didn't work. The different place is that my environment is in a DOCKER. How can I solve it?

I'm too stupid. I forget to add '-I/usr1/pycparser-master/utils/fake_libc_include'  to cpp_args.
After adding it. I found pycparser works well on my PC
