### ISSUE TITLE
_Atomic support broken

### ISSUE THREAD

**Issue by stevetremblett** [eliben/pycparser#476]
Hmmmm, I tried, but the implementation is still incorrect, as `typedef _Atomic(_Bool) atomic_bool;` does not parse. This comes from e.g. LLVM `<stdatomic.h>`. I believe that is what my following code handled:

```python
    # This is a bit ugly, but we need to process atomic specifier before qualifiers,
    # since _Atomic(int) has a conflict with _Atomic int.
    def p_declaration_specifiers_no_type_4(self, p):
        """ declaration_specifiers_no_type  : atomic_specifier declaration_specifiers_no_type_opt
        """
        p[0] = self._add_declaration_specifier(p[2], p[1], 'type')
```

_Originally posted by @vit9696 in https://github.com/eliben/pycparser/issues/430#issuecomment-920053179_

I am witnessing this error on the current release version.

**Comment by stevetremblett** [comment]
`(pycparser-venv) sjt@deb-vm:~/work/pycparser-venv/pycparser/examples$ python ./dump_ast.py ~/Projects/ISARA/Builds/Toolkit/3.0/linux/samples/hash/hash_main.c 
Traceback (most recent call last):
  File "/home/sjt/work/pycparser-venv/pycparser/examples/./dump_ast.py", line 29, in <module>
    ast = parse_file(args.filename, use_cpp=True)
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/c_parser.py", line 1858, in p_error
    self._parse_error(
  File "/home/sjt/work/pycparser-venv/lib/python3.9/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /home/sjt/work/pycparser-venv/pycparser/utils/fake_libc_include/_fake_typedefs.h:175:24: before: atomic_bool
`

**Comment by stevetremblett** [comment]
![Screen Shot 2022-10-30 at 8 47 03 AM](https://user-images.githubusercontent.com/117018838/198879284-10301228-eb06-47a5-99c6-2a8de675c4ca.png)

**Comment by eliben** [comment]
Please do not post screenshots of code or output. Paste a minimal yet complete reproducer instead.
