### ISSUE TITLE
Can't parse like this “for (iLoop = 0; iLoop < g_stNotesParams.iNoteNums; (void)({iLoop++;b=iLoop;}))”

### ISSUE THREAD

**Issue by xkey3960** [eliben/pycparser#483]
I wrote some code like this：
```
void testPrintNotes()
{
    int iLoop = 0;
    int b=0;
    for (iLoop = 0; iLoop < g_stNotesParams.iNoteNums; (void)({iLoop++;b=iLoop;}))
    {
        printf("%s\n", g_stNotesParams.acNotesNames[iLoop]);
    }
}
```

It can work well in Linux（actually in WSL）：
```
$ uname -a
Linux DESKTOP-JHULLF6 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

But the pycparser cannot parse the code, and raise the error：
```
Traceback (most recent call last):
  File "func_calls.py", line 75, in <module>
    ast = parse_file('./codes/notes.c', use_cpp=True, cpp_path='gcc', cpp_args=['-E','-I/home/xkey/WorkSpace/pycparser/utils/fake_libc_include/'])
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/home/xkey/.local/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: ./codes/notes.c:35:63: before: {
```

**Comment by eliben** [comment]
Please provide a complete, minimal reproducer.

**Comment by xkey3960** [comment]
> Please provide a complete, minimal reproducer.

c file:
``` c
#include <stdio.h>
#include <stdlib.h>

void printArray()
{
    int iLoop = 0;
    int iTest = 0;

    for (iLoop = 0; iLoop<10; (void)({iLoop++;iTest=iLoop;}))
    {
        printf("%d ", iLoop);
    }
}

int main(int argc, char *argv[])
{
    printArray();
    return 0;
}
```

python file:
``` python
from __future__ import print_function
import sys

from pycparser import c_parser, c_ast, parse_file, c_generator

if __name__ == "__main__":
    print('start')
    filename = './TestPycparser.c'
    args = ['-E','-I/home/xkey/pycparser/utils/fake_libc_include/']
    ast = parse_file(filename, use_cpp=True, cpp_path='gcc', cpp_args=args)
    print(ast)
```

error info:
```
$ python3 func_calls.py 
start
Traceback (most recent call last):
  File "func_calls.py", line 10, in <module>
    ast = parse_file(filename, use_cpp=True, cpp_path='gcc', cpp_args=args)
  File "/usr/local/lib/python3.8/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python3.8/dist-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.8/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.8/dist-packages/pycparser/c_parser.py", line 1945, in p_error
    self._parse_error(
  File "/usr/local/lib/python3.8/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: ./TestPycparser.c:9:38: before: {
```

env:
```
$ uname -a
Linux DESKTOP-G4M19EK 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
```

**Comment by eliben** [comment]
I suspect this is a GCC extension (statement expressions0, not standard C, which is why pycparser refuses to parse it.

```
$ gcc -pedantic  -std=c99 -c /tmp/3.c 
/tmp/3.c: In function ‘printArray’:
/tmp/3.c:7:37: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
    7 |     for (iLoop = 0; iLoop<10; (void)({iLoop++;iTest=iLoop;}))
      |                                     ^
```
