### ISSUE TITLE
PyCParser Parsing error on __attribute__ ((

### ISSUE THREAD

**Issue by acverbeck** [eliben/pycparser#73]
Eli,

I am trying to use pycparser to do static testing on embedded C. I am using pycparser v2.10.

The target code can be compiled by gcc and a cpp @ccargs.txt i2cm_5410x.c (testing against a master i2c driver) seems to be OK. I have created a configuration file which seems to be working fine (ccargs.txt). In it, I have the include files and defines that are required to compile the module.  All this seems to be working fine.

When I run my modified version of cpp_libc.py, I receive a parsing error. Here is the traceback.

Traceback (most recent call last):
  File "cpp_libc.py", line 27, in <module>
    cpp_args=r'@ccargs.txt')
  File "build\bdist.win32\egg\pycparser\__init__.py", line 93, in parse_file
  File "build\bdist.win32\egg\pycparser\c_parser.py", line 138, in parse
  File "build\bdist.win32\egg\pycparser\ply\yacc.py", line 265, in parse
  File "build\bdist.win32\egg\pycparser\ply\yacc.py", line 1047, in parseopt_notrack
  File "build\bdist.win32\egg\pycparser\c_parser.py", line 1613, in p_error
  File "build\bdist.win32\egg\pycparser\plyparser.py", line 54, in _parse_error
pycparser.plyparser.ParseError: ../inc/core_cmInstr.h:325:16: before: (

The  function it is complaining about is this:
__attribute__( ( always_inline ) ) __STATIC_INLINE void __NOP(void)
{
  __ASM volatile ("nop");
}

Specifically, the first line (__attribute__) at the second open "("... Any idea what may be causing this?

Thanks,

ACV

**Comment by eliben** [comment]
Does this help you?

https://github.com/eliben/pycparser/wiki/FAQ#what-do-i-do-about-__attribute__

**Comment by acverbeck** [comment]
I just re-read the docs...
I see that pycparser doesn't support any gcc extesions.
And yes, your comment does help.  Thanks for the very quick response.

ACV

**Comment by kirbyfan64** [comment]
Also, you can try [pycparserext](https://pypi.python.org/pypi/pycparser), which implements GCC extensions for pycparser.
