### ISSUE TITLE
Extract all extern function from c ?

### ISSUE THREAD

**Issue by gcmartijn** [eliben/pycparser#94]
Is it possible to extract all the external functions that are usable from this c/c++ lib ?
https://www.libsdl.org/index.php

**Comment by eliben** [comment]
Yes.

You can get started by perusing this example: https://github.com/eliben/pycparser/blob/master/examples/func_defs.py and then adapting as you go

**Comment by gcmartijn** [comment]
yea I did but I get several errors when I try things.


    if __name__ == "__main__":
        show_func_defs('/Users/gcmartijn/downloads/SDL2-2.0.3/src/SDL.c')

Traceback (most recent call last):
  File "/Users/gcmartijn/Downloads/test.py", line 28, in <module>
    show_func_defs('/Users/gcmartijn/downloads/SDL2-2.0.3/src/SDL.c')
  File "/Users/gcmartijn/Downloads/test.py", line 21, in show_func_defs
    ast = parse_file(filename, use_cpp=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/c_parser.py", line 552, in p_pp_directive
    self._coord(p.lineno(1)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/TargetConditionals.h:88: Directives not supported yet

**Comment by eliben** [comment]
It seems like system headers are being included (`SDKs/MacOSX10.10.sdk/usr/include/TargetConditionals.h`) -- it's best to avoid this. See http://eli.thegreenplace.net/2009/05/22/faking-standard-c-header-files-for-pycparser for details
